import type { AnalyzeRequest, Env, LlmScoredFields } from "./types";
import { clamp01 } from "./scoring";

interface AnthropicToolUse {
  type: "tool_use";
  name: string;
  input: Record<string, unknown>;
}

const SCORE_TOOL = {
  name: "return_content_risk_score",
  description: "Return synthetic content and slop risk scoring as strict structured data.",
  input_schema: {
    type: "object",
    properties: {
      synthetic_risk: { type: "number", minimum: 0, maximum: 1 },
      slop_risk: { type: "number", minimum: 0, maximum: 1 },
      confidence: { type: "string", enum: ["low", "medium", "high"] },
      evidence: {
        type: "array",
        maxItems: 5,
        items: {
          type: "object",
          properties: {
            type: { type: "string" },
            severity: { type: "string", enum: ["low", "medium", "high"] },
            span: { type: "string", maxLength: 120 },
            explanation: { type: "string", maxLength: 240 },
          },
          required: ["type", "severity", "span", "explanation"],
          additionalProperties: false,
        },
      },
      recommended_fixes: {
        type: "array",
        maxItems: 5,
        items: { type: "string", maxLength: 240 },
      },
    },
    required: ["synthetic_risk", "slop_risk", "confidence", "evidence", "recommended_fixes"],
    additionalProperties: false,
  },
};

export async function scoreText(input: AnalyzeRequest, env: Env): Promise<LlmScoredFields> {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 15_000);
  const model = env.ANTHROPIC_MODEL || "claude-haiku-4-5-20251001";

  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      signal: controller.signal,
      headers: {
        "content-type": "application/json",
        "x-api-key": env.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model,
        max_tokens: 900,
        temperature: 0,
        system:
          "You are a content trust analyst. Score text for synthetic/AI-generated risk and slop (low-value, generic content) risk. Use the tool exactly once. Do not overclaim; this is probabilistic risk scoring, not proof of authorship.",
        messages: [
          {
            role: "user",
            content: buildPrompt(input),
          },
        ],
        tools: [SCORE_TOOL],
        tool_choice: { type: "tool", name: "return_content_risk_score" },
      }),
    });

    if (!res.ok) {
      const body = await res.text();
      throw new LlmError(`Anthropic returned ${res.status}: ${body.slice(0, 300)}`);
    }

    const data = (await res.json()) as { content?: Array<AnthropicToolUse | Record<string, unknown>> };
    const toolUse = data.content?.find((item): item is AnthropicToolUse => item.type === "tool_use" && item.name === "return_content_risk_score");
    if (!toolUse) throw new LlmError("Anthropic response did not include expected tool_use");
    return normalizeScoredFields(toolUse.input);
  } catch (err) {
    if (err instanceof LlmError) throw err;
    if (err instanceof DOMException && err.name === "AbortError") throw new LlmError("Anthropic request timed out");
    throw new LlmError(err instanceof Error ? err.message : "Unknown Anthropic error");
  } finally {
    clearTimeout(timeout);
  }
}

function buildPrompt(input: AnalyzeRequest): string {
  return `Score the following English text for content trust risk.

Return only by calling the provided tool.

Scoring guidance:
- synthetic_risk: probability the text was generated by an LLM. Signals: generic phrasing, even cadence, template structure, absence of firsthand detail or specific named entities, hedging.
- slop_risk: probability the text is low-value/generic regardless of authorship. Signals: vague generalities, repeated transitions, listicle bloat, no concrete claims.
- Calibrate to format: ${input.context.format}
- Calibrate to intended use: ${input.context.intended_use}
- Domain: ${input.context.domain || "general"}
- Short text under 100 words should usually return confidence low.
- Evidence spans must be verbatim quotes from the text.

Text:\n"""\n${input.text}\n"""`;
}

function normalizeScoredFields(raw: Record<string, unknown>): LlmScoredFields {
  const confidence = raw.confidence === "high" || raw.confidence === "medium" || raw.confidence === "low" ? raw.confidence : "low";
  const evidenceRaw = Array.isArray(raw.evidence) ? raw.evidence.slice(0, 5) : [];
  const evidence = evidenceRaw.map((item) => {
    const obj = typeof item === "object" && item ? (item as Record<string, unknown>) : {};
    const rawSeverity = obj.severity;
    const severity: "low" | "medium" | "high" = rawSeverity === "high" || rawSeverity === "medium" || rawSeverity === "low" ? rawSeverity : "low";
    return {
      type: String(obj.type || "unspecified_signal").slice(0, 80),
      severity,
      span: String(obj.span || "").slice(0, 120),
      explanation: String(obj.explanation || "").slice(0, 240),
    };
  });
  const fixes = Array.isArray(raw.recommended_fixes) ? raw.recommended_fixes.slice(0, 5).map((x) => String(x).slice(0, 240)) : [];
  return {
    synthetic_risk: clamp01(raw.synthetic_risk),
    slop_risk: clamp01(raw.slop_risk),
    confidence,
    evidence,
    recommended_fixes: fixes,
  };
}

export class LlmError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "LlmError";
  }
}
